### ISSUE TITLE
CSS实现六边形的几种方法

### ISSUE THREAD

**Issue by iamwelk** [iamwelk/blog#1]
如题目所示，整理了一下用`css`绘制六边形的几种方式，以供参考  
### 第一种：伪元素 + 边框
``` css
.hexagon{
    position: relative;
    margin: 50px 0;
    height: 100px;
    width: 173px; // sqrt(3) * height
    background: #eee;
    border-color: #eee;
}

.hexagon::before {
    position: absolute;
    content: '';
    top: -50px; // -0.5 * height
    left: 0;
    border-top: none;
    border-left: 86.5px solid transparent;
    border-right: 86.5px solid transparent;
    border-bottom: 50px solid;
    border-bottom-color: inherit;
}

.hexagon::after {
    position: absolute;
    content: '';
    bottom: -50px; // -0.5 * height
    left: 0;
    border-top: 50px solid;
    border-top-color: inherit;
    border-left: 86.5px solid transparent;
    border-right: 86.5px solid transparent;
    border-bottom: none;
}
```  
最终结果  
![image](https://user-images.githubusercontent.com/6983075/30946503-06d69eb0-a437-11e7-9559-2c0549dd04f0.png)

### 第二种：clip-path
``` css
.hexagon{
    position: relative;
    height: 200px;
    width: 173px;
    background: #eee;
    clip-path: polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%);
}
```  
最终结果  
![image](https://user-images.githubusercontent.com/6983075/30946606-a0c6e2a0-a437-11e7-85af-189003e89955.png)

### 第三种：伪元素 + clip-path
``` css
.hexagon{
    position: relative;
    margin: 50px 0;
    height: 100px;
    width: 173px;
    background: #eee;
}

.hexagon::before {
    position: absolute;
    content: '';
    display: block;
    top: -50px;
    left: 0;
    width: 100%;
    height: 50px;
    background: inherit;
    clip-path: polygon(50% 0, 100% 100%, 0 100%);
}

.hexagon::after {
    position: absolute;
    content: '';
    display: block;
    bottom: -50px;
    left: 0;
    width: 100%;
    height: 50px;
    background: inherit;
    clip-path: polygon(100% 0, 50% 100%, 0 0);
}
```
最终结果
![image](https://user-images.githubusercontent.com/6983075/30946769-7a71a4e0-a438-11e7-920f-d7efa329ee95.png)

### 第四种：同3
``` css
.hexagon {
    position: relative;
    margin: 50px 0;
    height: 100px;
    width: 173px;
    background: #eee;
}

.hexagon::before {
    position: absolute;
    content: '';
    display: block;
    top: -50px;
    left: 0;
    width: 100%;
    height: 200px;
    background: inherit;
    clip-path: polygon(50% 0, 100% 25%, 100% 75%, 50% 100%, 0 75%, 0 25%);
    cursor: pointer;
}

.hexagon:hover {
    background: #ccc;
}
```
