### ISSUE TITLE
几种设置0.5px边框的方法

### ISSUE THREAD

**Issue by iamwelk** [iamwelk/blog#39]
## 使用box-shadow
```
box-shadow: 0.5px 0.5px #f00, 0.5px 0.5px #f00 inset;
```

## scale的方式
``` css
.box {
      position: relative;

      &:before {
        content: '';
        position: absolute;
        left: 0;
        top: 0;
        border: 1px solid #42b983;
        width: 200%;
        height: 200%;
        transform: scale(0.5, 0.5);
        transform-origin: 0 0;
      }
    }
// 原理：先放大两倍，设置1px的边框，再缩放为当前的二分之一，边框就同时被缩放为0.5px了
```
